name: Validate packer template

on:
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: 1.10.1

      - name: Run `packer fmt`
        run: "packer fmt -check ./gcp-centos8.pkr.hcl"

      - name: Run `packer init`
        id: init
        run: "packer init ./gcp-centos8.pkr.hcl"

      - name: Run `packer validate`
        id: validate
        run: |
          packer validate -var 'project_id='${{ secrets.GCP_PROJECT_ID }} \
          -var 'jasypt_encryption_key='${{ secrets.JASYPT_ENCRYPTION_KEY }} \
          -var 'zone='${{ secrets.GCP_ZONE }} ./gcp-centos8.pkr.hcl
