# This workflow will compile a package using Maven and then publish it to GitHub packages when a release is created
name: Build machine image

on:
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: "8.0"
          root-password: ${{ secrets.MYSQL_ROOT_PASSWORD }}

      - name: Install Package
        run: mvn -B clean install -Djasypt.encryptor.password=${{ secrets.JASYPT_ENCRYPTION_KEY }}

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_ACCOUNT_JSON }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Use gcloud CLI
        run: gcloud info

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: 1.10.1

      - name: Run `packer fmt`
        run: "packer fmt -check ./gcp-centos8.pkr.hcl"

      - name: Run `packer init`
        id: init
        run: "packer init ./gcp-centos8.pkr.hcl"

      - name: Run `packer validate`
        id: validate
        run: |
          packer validate -var 'mysql_password='${{ secrets.MYSQL_ROOT_PASSWORD }} \
          -var 'project_id='${{ secrets.GCP_PROJECT_ID }}
          -var 'zone='${{ secrets.GCP_ZONE }} ./gcp-centos8.pkr.hcl

      - name: Build Image
        run: | 
          packer build -on-error=abort -var 'MYSQL_PASSWORD='${{ secrets.MYSQL_ROOT_PASSWORD }} \
          -var 'project_id='${{ secrets.GCP_PROJECT_ID }}
          -var 'zone='${{ secrets.GCP_ZONE }} ./gcp-centos8.pkr.hcl
